### ISSUE TITLE
BUG: Title limit not applied for new topic title

### ISSUE THREAD

**Issue by tiblu** [citizenos/ep_title_limit#1]
**Reproduce**

* Create a new Topic in Citizen OS
* Type title longer than 100 characters

![image](https://user-images.githubusercontent.com/7405383/74157760-8196d900-4c21-11ea-8ed4-dc99d768f08c.png)

**Result**

* No title too long notification displayed

**Expected**

* Title too long notification displayed instantly while typing over the 100 char limit

![image](https://user-images.githubusercontent.com/7405383/74157818-9d01e400-4c21-11ea-9283-a7db14a62f31.png)

**Other notes**

* It starts working correct once you delete a character from the title
* It works properly if you reload the page after creating a long title for a Topic

**Comment by loorm** [comment]
Triage 18: classified as a bug. ETA unknown. @ilmartyrk - can you estimate, how long fixing will take?

**Comment by ilmartyrk** [comment]
@loorm @tiblu ETA about 1 hour

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/ep_title_limit/commit/f8de692870bb7e45baafa06fbe6740702f4eab5f

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working.
